[package]
name = "tentacle-identify"
version = "0.2.2"
authors = ["Qian Linfeng <thewawar@gmail.com>"]
license = "MIT"
description = "p2p identify protocol"
keywords = ["network", "peer-to-peer", "p2p", "identify"]
repository = "https://github.com/nervosnetwork/p2p"
categories = ["network-programming", "asynchronous"]
edition = "2018"

[dependencies]
p2p = { path = "../..", version = "0.2.0-alpha.7", package = "tentacle" }
bytes = "0.4"
flatbuffers = "0.5.0"
flatbuffers-verifier = "0.1.8"
tokio = "0.1"
log = "0.4"
