[package]
name = "tentacle-secio"
version = "0.1.7"
license = "MIT"
description = "Secio encryption protocol for p2p"
authors = ["piaoliu <441594700@qq.com>", "Nervos Core Dev <dev@nervos.org>"]
repository = "https://github.com/nervosnetwork/p2p"
keywords = ["network", "peer-to-peer"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"
log = "0.4.1"

flatbuffers = "0.6.0"
flatbuffers-verifier = "0.2.0"

secp256k1 = "0.12"
hmac = "0.7.0"
sha2 = "0.8.0"
rand = "0.6"
ring = "0.14.0"
twofish = "0.2.0"
untrusted = "0.6.2"
aes-ctr = "0.3.0"
ctr = "0.3.0"
unsigned-varint = "0.2.2"
bs58 = "0.2.0"

[dev-dependencies]
env_logger = "0.6"
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
