[package]
name = "secio"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio = "0.1"
log = "0.4.1"

secp256k1 = "0.12"
hmac = "0.7.0"
sha2 = "0.8.0"
rand = "0.6"
ring = "0.13.5"
twofish = "0.2.0"
untrusted = "0.6.2"
aes-ctr = "0.3.0"
ctr = "0.3.0"

[dev-dependencies]
env_logger = "0.6"
