language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - RUSTFLAGS='-F warnings' cargo build --all
  - cargo build --examples --all
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      script:
        - RUSTFLAGS='-F warnings' cargo clippy --all --tests
    - stage: Test
      name: Unitest
      script:
        - RUSTFLAGS='-F warnings' cargo test --all
    - stage: Test
      name: Bench
      script:
        - cd bench
        - cargo run --release
