dist: bionic
language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
stages:
  - Build
  - Check
  - Test
jobs:
  include:
    - stage: Build
      script:
        - make build
        - make examples
    - stage: Check
      name: Format
      script:
        - make fmt
    - stage: Check
      name: Clippy
      script:
        - make clippy
    - stage: Test
      name: Unitest
      script:
        - make test
    - stage: Test
      name: Features check
      script:
        - make features-check
    - stage: Test
      name: Bench
      script:
        - make bench_p2p
    - stage: Test
      name: Fuzz
      script:
        - rustup install nightly
        - cargo +nightly install cargo-fuzz
        - make fuzz
