[package]
name = "tentacle-ping"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
license = "MIT"
keywords = ["network", "peer-to-peer", "p2p", "ping"]
categories = ["network-programming", "asynchronous"]
repository = "https://github.com/nervosnetwork/p2p"
description = "ping protocol implementation for tentacle"
edition = "2018"

[dependencies]
p2p = { path = "../..", package = "tentacle" }
log = "0.4"
flatbuffers = "0.5.0"
fnv = "1.0.6"
generic-channel = "0.2.0"
bytes = "0.4"
