[package]
name = "ping"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
p2p = { path = "..", package = "p2p" }
futures = "0.1"
tokio = "0.1"
log = "0.4"
flatbuffers = "0.5.0"
fnv = "1.0.6"
