[package]
name = "tokio-yamux"
version = "0.1.3"
license = "MIT"
repository = "https://github.com/nervosnetwork/p2p"
description = "Rust implementation of Yamux"
authors = ["Linfeng Qian <thewawar@gmail.com>", "Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
bytes = "0.4"
byteorder = "1.2"
fnv = "1.0"
futures = "0.1"
tokio = "0.1"
log = "0.4"

[dev-dependencies]
env_logger = "0.6"
